kind: Service
apiVersion: v1
metadata:
  name: nginx-deployment
  namespace: kong
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: kong
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
    #   # serviceAccountName: kongcpkongekscpcpascpsaf81c3957
    #   volumes:
    #   - name: secrets-store-inline
    #     csi:
    #       driver: secrets-store.csi.k8s.io
    #       readOnly: true
    #       volumeAttributes:
    #         secretProviderClass: "rds-secrets"
      containers:
      - name: nginx-deployment
        image: nginx
        ports:
        - containerPort: 80
        env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: rds-secrets
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rds-secrets
                key: password
        # volumeMounts:
        # - name: secrets-store-inline
        #   mountPath: "/mnt/secrets-store/arn:aws:secretsmanager:us-east-2:256151769638:secret:KongEksCpKongRdsPGInstanceS-ERYpGCatMLm3-hSRR2A"
        #   readOnly: true
